# Feedforward Neural Network

In [1]:
import torch
from utils import draw_function

ModuleNotFoundError: No module named 'utils'

In [2]:
torch.manual_seed(70)
x = torch.Tensor([[0,1]])

""" input > hidden """
w1 = torch.rand((2,2))
b1 = torch.rand((1,2))

# 은닉층 forward
z1 = torch.mm(x, w1.t()) + b1
a1 = torch.sigmoid(z1)

# 손실함수: 항등함수
def identity_func(x):
    return x

""" hidden > input """
w2 = torch.rand((1,2))
b2 = torch.rand((1,1))

# 출력층 forward
z2 = torch.mm(a1, w2.t()) + b2
y = identity_func(z2)

In [3]:
x

tensor([[0., 1.]])

In [4]:
w1

tensor([[0.4350, 0.3591],
        [0.3411, 0.2644]])

In [5]:
b1

tensor([[0.6656, 0.1341]])

In [6]:
import torch.nn as nn

torch.manual_seed(70)

# 선형결합, sigmoid 모듈 선언
# input > hidden
linear_ih = nn.Linear(in_features=2, out_features=2)
# hidden > output
linear_ho = nn.Linear(in_features=2, out_features=1)
activation_layer = nn.Sigmoid()

# forward 과정
z1 = linear_ih(x)
a1 = activation_layer(z1)
z2 = linear_ho(a1)
y = identity_func(z2)
print(y.item())

# 선형1-->활성-->선형2-->손실-->y

-0.3213229477405548


## 더 자주 사용하는 PyTorch스러운 방법
## - class객체로 사용자 정의 신경망 모듈 만들기

In [7]:
torch.manual_seed(70)

class Network(nn.Module):
    """ XOR Network """
    def __init__(self, input_size, hidden_size, output_size):
        super(Network, self).__init__()
        
        # input > hidden
        self.linear_ih = nn.Linear(in_features=input_size,
                                  out_features = hidden_size)
        
        # hidden > output
        self.linear_ho = nn.Linear(in_features=hidden_size,
                                  out_features=output_size)
        
        # activation layer
        self.activation_layer = nn.Sigmoid()
        
    def identity_func(self, x):
        return x
    
    def forward(self, x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.identity_func(z2)
        return y
    
# 커스텀 모듈 호출
net = Network(input_size=2, hidden_size=2, output_size=1)
y = net(x)
print(y.item())

-0.3213229477405548


In [8]:
y

tensor([[-0.3213]], grad_fn=<AddmmBackward0>)