In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch

print("torch: {} \n numpy: {}".format(torch.__version__, np.__version__))
print("USE GPU? {}".format(torch.cuda.is_available()))

torch: 1.13.1+cpu 
 numpy: 1.22.3
USE GPU? False


# 텐서를 만드는 방법

In [2]:
# 리스트로부터 2*3 텐서 생성 
x_list = [[1,2,3], [4,5,6]]
x = torch.Tensor(x_list)
print(x)

# numpy array 로부터 2*3 텐서 생성
x_numpy = np.array([[1,2,3], [4,5,6]])
x = torch.Tensor(x_numpy)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 다시 원래 자료형태로 복귀

In [3]:
x_back2list = x.tolist()
print(x_back2list)
print(type(x_back2list))

x_back2numpy = x.numpy()
print(x_back2numpy)
print(type(x_back2numpy))

print(x) # 해당 텐서 x는 그대로

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
<class 'list'>
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
tensor([[1., 2., 3.],
        [4., 5., 6.]])
